# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68108a24163b0e2e2577280cbf530814dcc0fccdac979c36a569f94a73fb376f661342f0957532db6e69ea62e833f69c9d345998ae939df125ffba95e8412bf4

test:
  secret_key_base: f437f72623ba6d8b0793122db71a73bd76cec1e4c78f1db141aa184a1411ec6f6de9e5f8fcedcd8f686be9c5d960aaa8a4e06c51deedcd0de58cc0d5d1a42178

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
